---
apiVersion: v1
kind: Service
metadata:
  annotations:
    jkube.eclipse.org/git-commit: f7b2dd9858476e7dc897b4b6e872d9b87c7d61b9
    jkube.eclipse.org/git-url: https://github.com/mohammad2java/argocd-yml-demo.git
    jkube.eclipse.org/git-branch: master
  labels:
    app: argocd-yml-demo
    provider: jkube
    version: 0.0.1-SNAPSHOT
    group: com.example
    app.kubernetes.io/part-of: com.example
    app.kubernetes.io/managed-by: jkube
    app.kubernetes.io/name: argocd-yml-demo
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: argocd-yml-demo
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: argocd-yml-demo
    provider: jkube
    group: com.example
    app.kubernetes.io/name: argocd-yml-demo
    app.kubernetes.io/part-of: com.example
    app.kubernetes.io/managed-by: jkube
  type: NodePort
